version: '3'
services:
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:${DATABASE_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
